name: Build website

on:
  workflow_call:
    secrets:
      netlify-token:
        required: true
      # To be able to use the `gh` cli in the workflow.
      github-token:
        required: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Spell check repo
        uses: crate-ci/typos@4d9c206a77c041268485162b8e2579ad7a5cb9a3 # v1.50.0

      - name: Setup R
        uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@465b7d8e732ca3921382b1674c59bada9cbf3399

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0

      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.netlify-token }}
